### ISSUE TITLE
selenium_start and selenium_phantom_hub hang with Jenkins running

### ISSUE THREAD

**Issue by earmstrongPeaksware** [levexis/grunt-selenium-webdriver#15]
Hello,

I am having an issue starting a selenium server when jenkins is running. I have tried on Ubuntu and Mac OSX with the same problem. After stopping jenkins, the selenium server starts up just fine. I am not sure if there is something I am missing. Jenkins is running on port 8080 while I have tried spinning up selenium on 4444 and 4445. Would love some guidance before attempting a different plugin.

Thanks,
Eric

**Comment by dcendents** [comment]
Looking at the code it looks like PhantomJS needs its own port and this is different from the selenium port. The default value is set to 8080 which will conflict with any standard jenkins installation. 

This was not clear to me after reading the main instructions, what are the two parameters port and phantomPort for and what are the default values.

To fix this simply define a different phantomPort:

```javascript
selenium_phantom_hub : {
	options : {
		// Using some random port, otherwise there is a conflict with jenkins
		phantomPort : 4786
	}
},
```

This starts selenium on default port 4444 and does not conflict with jenkins on 8080.

**Comment by levexis** [comment]
Thanks, that sounds correct to me. Any chance you could update the docs for Jenkins users and submit a PR?
