### ISSUE TITLE
Fatal error on recent Node 0.12 release: options must be object.

### ISSUE THREAD

**Issue by sholladay** [levexis/grunt-selenium-webdriver#16]
I have a simple configuration which is reliably *succeeding* on **Node 0.10.x** machines and *failing* on those with **Node 0.12.0**.
````javascript
selenium_start : {
    options : {
        port : 4447  // Override Selenium default of 4444, which is taken on OS X Server
    }
}
````

The error message is very misleading. Using Grunt's `--verbose` flag, this is what I see.
````bash
Options: timeout=false, host="127.0.0.1", port=4447, maxSession=false, cwd=null
Warning: options argument must be an object Use --force to continue.
````

Using Grunt's `--force` flag makes no difference, and simply leads to stuff like this from tasks that try to make use of the server.
````bash
Error: connect ECONNREFUSED
````

**Comment by levexis** [comment]
Not tested it on 0.12.0. Are you sure the port is free as it say connection refused, maybe worth using killall on the java process to be sure. First step is to test selenium from the command line? I'm quite busy this week so may not be able to take a look until the weekend.

**Comment by sholladay** [comment]
The port 4447 is definitely free, confirmed using a number of strategies, including `sudo lsof -i:4447`. The selenium server never starts, due to this `options argument must be an object` error. But other grunt tasks with similar configs succeed on the same platform. So I'm convinced it is a logic or parsing problem inside of the grunt-selenium-webdriver module.

**Comment by sholladay** [comment]
@levexis I have a fix for this: https://github.com/levexis/grunt-selenium-webdriver/pull/17

A workaround for anyone that doesn't feel like upgrading is also available:
````javascript
selenium_start : {
    options : {
        cwd : process.cwd()   // <-- this can actually be whatever path you want
    }
}
````

The reason this works is because `grunt-selenium-webdriver` checks the options object for a truthy 'cwd' property value, and it only goes down the erroring code path if it doesn't find one.

**Comment by justinjmoses** [comment]
This also affected iojs 1.3 (as you'd expect). 0.2.432 fixed it as expected.
