### ISSUE TITLE
Autoscan ports and/or inform the environment about the port.

### ISSUE THREAD

**Issue by sholladay** [levexis/grunt-selenium-webdriver#22]
There are many options for launching Selenium entirely from Node, but this module is one of my favorites primarily because it is very resilient and robust. However, there is one area where I desperately wish it was like [selenium-launcher](https://github.com/daaku/nodejs-selenium-launcher), which is to not make assumptions about which ports are available and, either way, to be able to inform other programs about which port was chosen.

My use case: OS X Server hogs Selenium's default port 4444, forcing me to ~~choose~~ assume something else. But then all of the downstream assumptions from test frameworks, etc. are broken. Let the non-DRY code commence!

Would you be open to a new config for saving the Selenium port on a property of process.env and, perhaps, [scanning](https://github.com/baalexander/node-portscanner) for it to begin with, to avoid EADDRINUSE errors?

**Comment by sholladay** [comment]
@levexis ^^

**Comment by levexis** [comment]
Hi, sorry for the radio silence - I've been busy on a project for a while and missed this. You can specify the ports in your Grunt file, I presume it gives you a suitable EADDRINUSE error if you do hit a port that's in use. Let me know if docs / error messages are not clear, am always happy to accept pull requests if you wish to fork.

**Comment by sholladay** [comment]
I no longer use Grunt. And my favorite framework, [Intern](https://github.com/theintern/intern), now has `SeleniumTunnel` which replaces this project for me. Sadly closing this as I'll probably never get around to it. A sincere thanks for all of your awesome work - this library served me and my team well for years.
